config/routes.rb
Eappscasts::Application.routes.draw do

  
    root :to => "info#home"

    match "auth/:provider/callback" => "sessions#create"
    match "/auth/failure", :to => "sessions#failure"
    match "twitter_login" => "sessions#twitter_login" ,:as=>"twitter_login"
    match "twitter_login_check" => "sessions#twitter_login_check" ,:as=>"twitter_login_check"
    match "/signout" => "sessions#destroy", :as => :signout
    match "about" => "info#about", :as => "about"
    match "login" => "info#login", :as => "login"
    match "opensource" => "info#opensource", :as => "opensource"
    match "give_back" => "info#give_back", :as => "give_back"
    match "contributors" => "info#contributors", :as => "contributors"
    match "logout" => "users#logout", :as => "logout"
    match "feedback" => "feedback_messages#new", :as => "feedback"
    match "episodes/archive" => redirect("/?view=list")
    match 'unsubscribe/:token' => 'users#unsubscribe', :as => "unsubscribe"
    post "versions/:id/revert" => "versions#revert", :as => "revert_version"
    get '/signup' => 'info#signup', :as => :signup  
  
    resources :users do
      member { put :ban }
    end
    resources :comments
    resources :episodes
    resources :feedback_messages

    match "tags/:id" => redirect("/?tag_id=%{id}")
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :episode, :counter_cache => true
  belongs_to :user

  validates_presence_of :content, :episode_id

  scope :recent, order("created_at DESC")

  has_paper_trail
  has_ancestry

  def self.search(query)
    if query.blank?
      scoped
    else
      conditions = %w[content name email site_url].map { |c| "comments.#{c} like :query" }
      where(conditions.join(" or "), :query => "%#{query}%")
    end
  end

  def request=(request)
    self.user_ip    = request.remote_ip
    self.user_agent = request.env['HTTP_USER_AGENT']
    self.referrer   = request.env['HTTP_REFERER']
  end

  def notify_other_commenters
    users_to_notify.each do |user|
      Mailer.comment_response(self, user).deliver
    end
  end

  def users_to_notify
    ancestors.map(&:user).compact.select { |u| u.email.present? && u.email_on_reply? && u != user }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @comments = @comments.search(params[:comment_search]).recent.paginate(:page => params[:page], :per_page => 50)
  end

  def new
    @comment = Comment.new(:parent_id => params[:parent_id], :episode_id => params[:episode_id], :user => current_user)
  end

  def create
    @comment = current_user.comments.build(params[:comment])
    @comment.request = request
    @comment.save
    respond_to do |format|
      format.html do
        if @comment.errors.present?
          render :new
        else
          @comment.notify_other_commenters
          redirect_to(episode_path(@comment.episode, :view => "comments"))
        end
      end
      format.js
    end
  end

  def edit
  end

  def update
    @comment.update_attributes(params[:comment])
    respond_to do |format|
      format.html do
        if @comment.errors.present?
          render :edit
        else
          redirect_to(episode_path(@comment.episode, :view => "comments"))
        end
      end
      format.js
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "Deleted comment. #{undo_link}"
    respond_to do |format|
      format.html { redirect_to episode_path(@comment.episode, :view => "comments") }
      format.js
    end
  end

  private

  def undo_link
    if can? :revert, :versions
      version = @comment.versions.scoped.last
      view_context.link_to("undo", revert_version_path(version), :method => :post) if can? :revert, version
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def format_comment(comment)
    if comment.legacy?
      simple_format(keep_spaces_at_beginning(h(comment.content)))
    else
      CodeFormatter.new(comment.content).to_html.html_safe
    end
  end

  def keep_spaces_at_beginning(content)
    content.split("\n").map do |line|
      line.sub(/^ +/) do |spaces|
        '&nbsp;' * spaces.length
      end
    end.join("\n")
  end

  def fix_url(url)
    if url =~ /^https?\:\/\//
      url
    else
      "http://#{url}"
    end
  end

  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <div class="avatar"><%= image_tag avatar_url(comment), :size => "64x64", :alt => "Avatar" %></div>
  <div class="actions user_actions">
    <%= link_to "Ban User", ban_user_path(comment.user), :confirm => "Are you certain you want to ban this user? It will delete all of his comments and not allow him to comment again.", :remote => true, :method => :put if comment.user && can?(:ban, comment.user) %>
  </div>
  <div class="main">
    <%= render "comments/comment_headline", :comment => comment %>
    <div class="comment_content">
      <%= format_comment(comment) %>
      <div class="actions">
        <%= link_to "Reply", new_comment_path(:parent_id => comment, :episode_id => comment.episode_id), :remote => true if can?(:create, :comments) %>
        <%= link_to "Edit", edit_comment_path(comment), :remote => true if can?(:update, comment) %>
        <%= link_to "Delete", comment, :method => :delete, :remote => true if can?(:destroy, comment) %>
      </div>
    </div>
  </div>
  <div class="clear"></div>
<% end %>

app/views/comments/_comment_headline.html.erb
<div class="headline">
  <% if comment.new_record? %>
    <span class="position">New comment as</span>
  <% end %>
  <span class="name">
    <% if comment.user %>
      <%= link_to comment.user.display_name, comment.user %>
    <% else %>
      <%= link_to_unless comment.site_url.blank?, comment.name, fix_url(comment.site_url), :rel => "nofollow" %>
    <% end %>
    <% if params[:controller] != "episodes" %>
      on <%= link_to comment.episode.full_name, episode_path(comment.episode, :view => "comments", :anchor => "comment_#{comment.id}") %>
    <% end %>
  </span>
  <% unless comment.created_at.nil? %>
    <%= link_to episode_path(comment.episode, :view => "comments", :anchor => "comment_#{comment.id}"), :class => "created_at" do %>
      <% if params[:controller] == "episodes" %>
        <%= time_ago_in_words comment.created_at %> ago
      <% else %>
        <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%I") %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<% if current_user.nil? %>
  <p>First <%= link_to "sign in through GitHub", login_path(:return_to => request.url) %> to post a comment.</p>
<% elsif cannot? :create, :comments %>
  <p>You have been banned from creating comments. Please <%= link_to "contact me", feedback_path %> if you are a legitimate user.</p>
<% else %>
  <%= div_for @comment do %>
    <div class="avatar"><%= image_tag avatar_url(@comment), :size => "64x64", :alt => "Avatar" %></div>
    <div class="main">
      <%= render "comments/comment_headline", :comment => @comment %>
      <div class="comment_content">
        <%= form_for @comment, :remote => true do |f| %>
          <%= f.error_messages %>
          <div>
            <%= f.hidden_field :episode_id %>
            <%= f.hidden_field :parent_id %>
          </div>
          <% if @comment.user_id && @comment.user_id != current_user.id %>
            <p><strong>Please follow the <%= link_to "moderator guidelines", moderators_path %>.</strong></p>
          <% end %>
          <div class="formatting">
            Use Markdown for formatting. <%= link_to "See examples.", "javascript:void(0)", :class => "markdown_link" %>
            <div class="markdown_examples" style="display: none">
              <table>
                <tr>
                  <td><pre>[Link](http://example.com/)</pre></td>
                  <td><a href="http://example.com/">Link</a></td>
                </tr>
                <tr>
                  <td><pre>*Italic*</pre></td>
                  <td><em>Italic</em></td>
                </tr>
                <tr>
                  <td><pre>**Bold**</pre></td>
                  <td><strong>Bold</strong></td>
                </tr>
                <tr>
                  <td><pre>
* Listed
* Items
                  </pre></td>
                  <td><ul><li>Listed</li><li>Items</li></ul></td>
                </tr>
                <tr>
                  <td><pre>&gt; Block quote</pre></td>
                  <td><blockquote><p>Block quote</p></blockquote></td>
                </tr>
                <tr>
                  <td><pre>`Inline code`</pre></td>
                  <td><code>Inline code</code></td>
                </tr>
                <tr>
                  <td>
                    <pre>
``` ruby
puts "code block"
```
                    </pre>
                  </td>
                  <td><%= raw CodeFormatter.new("``` ruby\nputs \"code block\"\n```").to_html %></td>
                </tr>
              </table>
            </div>
          </div>
          <div class="field">
            <%= f.text_area :content, :rows => '12', :cols => 65 %>
          </div>
          <% if @comment.legacy? %>
          <div class="field">
            <%= f.check_box :legacy %>
            <%= f.label :legacy, "Legacy comment (markdown disabled)", :class => "check_box" %>
          </div>
          <% end %>
          <div class="actions">
            <%= f.submit(@comment.new_record? ? "Post Comment" : "Update Comment") %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="clear"></div>
  <% end %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.parent_id.present? %>
  var container = $("#<%= dom_id(@comment.parent) %>").next(".nested_comments");
<% else %>
  var container = $("#comments");
<% end %>
<% if @comment.errors.present? %>
  container.find("form").prepend("<%= escape_javascript error_messages_for(@comment) %>");
<% else %>
  container.children("#new_comment").replaceWith("<%= escape_javascript render(@comment) %>");
<% end %>

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").replaceWith("<%= escape_javascript("<p>#{flash.delete(:notice)}</p>".html_safe) %>");

app/views/comments/edit.html.erb
<% title "Edit Comment" %>

<div class="content">
  <%= render "form" %>
</div>

app/views/comments/edit.js.erb
$("#<%= dom_id(@comment) %>").replaceWith("<%= escape_javascript render("form") %>");
$("#<%= dom_id(@comment) %>").find("#comment_content")[0].focus();

app/views/comments/index.html.erb
<% title "Recent Comments" %>

<div class="content">
  <%= form_tag comments_path, :method => :get do %>
    <p>
      <%= text_field_tag :comment_search, params[:comment_search] %>
      <%= submit_tag "Search Comments", :name => nil %>
    </p>
  <% end %>
  <div id="comments">
    <%= will_paginate :previous_label => h("< Previous Page"),  :next_label => h("Next Page >") %>
    <%= render @comments %>
    <%= will_paginate :previous_label => h("< Previous Page"),  :next_label => h("Next Page >") %>
  </div>
</div>

app/views/comments/new.html.erb
<% title "New Comment" %>

<div class="content">
  <%= render "form" %>
</div>

app/views/comments/new.js.erb
if ($("#comment_<%= params[:parent_id] %>").next(".nested_comments").children("#new_comment").length == 0) {
  $("#comment_<%= params[:parent_id] %>").next(".nested_comments").prepend("<%= escape_javascript render("form") %>");
  $("#comment_<%= params[:parent_id] %>").next(".nested_comments").find("#comment_content")[0].focus();
}

app/views/comments/update.js.erb
<% if @comment.errors.present? %>
  $("#<%= dom_id(@comment) %>").find("form").prepend("<%= escape_javascript error_messages_for(@comment) %>");
<% else %>
  $("#<%= dom_id(@comment) %>").replaceWith("<%= escape_javascript render(@comment) %>");
<% end %>