config/routes.rb
Eappscasts::Application.routes.draw do

  
    root :to => "info#home"

    match "auth/:provider/callback" => "sessions#create"
    match "/auth/failure", :to => "sessions#failure"
    match "twitter_login" => "sessions#twitter_login" ,:as=>"twitter_login"
    match "twitter_login_check" => "sessions#twitter_login_check" ,:as=>"twitter_login_check"
    match "/signout" => "sessions#destroy", :as => :signout
    match "about" => "info#about", :as => "about"
    match "login" => "info#login", :as => "login"
    match "opensource" => "info#opensource", :as => "opensource"
    match "give_back" => "info#give_back", :as => "give_back"
    match "contributors" => "info#contributors", :as => "contributors"
    match "logout" => "users#logout", :as => "logout"
    match "feedback" => "feedback_messages#new", :as => "feedback"
    match "episodes/archive" => redirect("/?view=list")
    match 'unsubscribe/:token' => 'users#unsubscribe', :as => "unsubscribe"
    post "versions/:id/revert" => "versions#revert", :as => "revert_version"
    get '/signup' => 'info#signup', :as => :signup  
  
    resources :users do
      member { put :ban }
    end
    resources :comments
    resources :episodes
    resources :feedback_messages

    match "tags/:id" => redirect("/?tag_id=%{id}")
  
end

app/models/user.rb
class User < ActiveRecord::Base
#  attr_accessible :name, :email, :site_url, :email_on_reply
  before_create { generate_token(:token) }
  has_many :comments
  has_paper_trail

  def self.create_from_omniauth(omniauth)


    case omniauth["provider"]

                when GlobalConstants::PROVIDER_TYPE[1]

                   user_id = omniauth["extra"][:access_token].params["user_id"]

                when GlobalConstants::PROVIDER_TYPE[2]

                   user_id = omniauth["uid"]

                when GlobalConstants::PROVIDER_TYPE[3]

                   user_id = omniauth["uid"]

                else

        end

   User.new.tap do |user|
      user.name = omniauth["info"]["name"]
      user.email = omniauth["info"]["email"]
      user.provider = omniauth["provider"]
      user.nickname = omniauth["info"]["nickname"]
      user.uid = user_id
      user.omniauth_hash = omniauth.to_yaml
      user.save!

    end
  end

  def self.update_from_omniauth(user_detail,omniauth)

    case omniauth["provider"]

                when GlobalConstants::PROVIDER_TYPE[1]

                   user_id = omniauth["extra"][:access_token].params["user_id"]

                when GlobalConstants::PROVIDER_TYPE[2]

                   user_id = omniauth["uid"]

                when GlobalConstants::PROVIDER_TYPE[3]

                   user_id = omniauth["uid"]

                else

        end


    @user_details = User.find_by_id(user_detail.id)
    @user_details.name = omniauth["info"]["name"]
      @user_details.email = omniauth["info"]["email"]
      @user_details.provider = omniauth["provider"]
      @user_details.nickname = omniauth["info"]["nickname"]
      @user_details.uid = user_id
      @user_details.omniauth_hash = omniauth.to_yaml
      @user_details.save!

   
    
  end


  def generated_unsubscribe_token
    if unsubscribe_token.blank?
      generate_token(:unsubscribe_token)
      save!
    end
    unsubscribe_token
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def display_name
    name.present? ? name : github_username
  end

  def banned?
    banned_at
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_filter :load_current_user, :only => [:edit, :update]
  before_filter :load_current_user

  load_and_authorize_resource

  def show
  end

  def create
   
    omniauth = request.env["omniauth.auth"]
    logger.info omniauth.inspect
    @user = User.find_by_github_uid(omniauth["uid"]) || User.create_from_omniauth(omniauth)
    cookies.permanent[:token] = @user.token
    redirect_to_target_or_default root_url, :notice => "Signed in successfully"
  end

  def edit
  end

  def update
    @user.attributes = params[:user]
    @user.save!
    redirect_to @user, :notice => "Successfully updated profile."
  end

  def login
    session[:return_to] = params[:return_to] if params[:return_to]
    if Rails.env.development?
      cookies.permanent[:token] = User.first.token
      redirect_to_target_or_default root_url, :notice => "Signed in successfully"
    else
      redirect_to "/auth/github"
    end
  end

  def logout
    cookies.delete(:token)
    redirect_to root_url, :notice => "You have been logged out."
  end

  def ban
    @user = User.find(params[:id])
    @user.update_attribute(:banned_at, Time.now)
    @comments = @user.comments
    @comments.each(&:destroy)
    respond_to do |format|
      format.html { redirect_to :back, :notice => "User #{@user.name} has been banned." }
      format.js
    end
  end

  def unsubscribe
    @user = User.find_by_unsubscribe_token!(params[:token])
    @user.update_attributes!(:email_on_reply => false)
    redirect_to root_url, :notice => "You have been unsubscribed from further email notifications."
  end

  private

  def load_current_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/ban.js.erb
<% @comments.each do |comment| %>
  $("#<%= dom_id(comment) %>").remove();
<% end %>

app/views/users/edit.html.erb
<% title "Edit Profile" %>

<div class="content">
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :site_url, "Site URL" %>
    <%= f.text_field :site_url %>
  </p>
  <p>
    <%= f.check_box :email_on_reply %>
    <%= f.label :email_on_reply, "Receive email when a user replies to your comment", :class => "check_box" %>
  </p>
  <p><%= f.submit "Update Profile" %></p>
<% end %>
</div>

app/views/users/show.html.erb
<% title "#{@user.display_name}'s Profile" %>

<div class="content">
  <% if @user == current_user %>
    <p><%= link_to "Edit Profile", edit_user_path(@user) %> | <%= link_to "Log Out", logout_path %></p>
    <p><strong>This is your profile.</strong></p>
  <% end %>
  <% if @user.moderator? %>
    <p><strong>This user is a moderator.</strong></p>
  <% end %>
  <% if @user.banned? %>
    <p><strong>This user is banned from comments.</strong></p>
  <% end %>
  <p>GitHub User: <%= link_to @user.github_username, "https://github.com/#{@user.github_username}" %></p>
  <% unless @user.site_url.blank? %>
    <p>Site: <%= link_to @user.site_url, fix_url(@user.site_url) %></p>
  <% end %>
  <div class="actions">
    <p><%= link_to "Ban this User", ban_user_path(@user), :confirm => "Are you certain you want to ban this user? It will delete all of his comments and not allow him to comment again.", :remote => true, :method => :put if can?(:ban, @user) && !@user.banned? %></p>
  </div>
  <h3>Comments by <%= @user.name %></h3>
  <div id="comments">
  <% for comment in @user.comments.recent %>
    <%= render comment %>
  <% end %>
  </div>
</div>