config/routes.rb
Eappscasts::Application.routes.draw do

  
    root :to => "info#home"

    match "auth/:provider/callback" => "sessions#create"
    match "/auth/failure", :to => "sessions#failure"
    match "twitter_login" => "sessions#twitter_login" ,:as=>"twitter_login"
    match "twitter_login_check" => "sessions#twitter_login_check" ,:as=>"twitter_login_check"
    match "/signout" => "sessions#destroy", :as => :signout
    match "about" => "info#about", :as => "about"
    match "login" => "info#login", :as => "login"
    match "opensource" => "info#opensource", :as => "opensource"
    match "give_back" => "info#give_back", :as => "give_back"
    match "contributors" => "info#contributors", :as => "contributors"
    match "logout" => "users#logout", :as => "logout"
    match "feedback" => "feedback_messages#new", :as => "feedback"
    match "episodes/archive" => redirect("/?view=list")
    match 'unsubscribe/:token' => 'users#unsubscribe', :as => "unsubscribe"
    post "versions/:id/revert" => "versions#revert", :as => "revert_version"
    get '/signup' => 'info#signup', :as => :signup  
  
    resources :users do
      member { put :ban }
    end
    resources :comments
    resources :episodes
    resources :feedback_messages

    match "tags/:id" => redirect("/?tag_id=%{id}")
  
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  has_paper_trail

  scope :published, lambda { where('published_at <= ?', Time.now.utc) }
  scope :unpublished, lambda { where('published_at > ?', Time.now.utc) }
  scope :tagged, lambda { |tag_id| tag_id ? joins(:taggings).where(:taggings => {:tag_id => tag_id}) : scoped }
  scope :recent, order('position DESC')

  validates_presence_of :published_at, :name
  serialize :file_sizes

  before_create :set_permalink

  # sometimes ThinkingSphinx isn't loaded for rake tasks
  if respond_to? :define_index
    define_index do
      indexes :name
      indexes position, :sortable => true
      indexes description
      indexes notes
      indexes comments.content, :as => :comment_content
      indexes tags(:name), :as => :tag_names

      has published_at
      has taggings.tag_id, :as => :tag_ids
    end
  end

  def self.search_published(query, tag_id = nil)
    if APP_CONFIG['thinking_sphinx']
      with = tag_id ? {:tag_ids => tag_id.to_i} : {}
      search(query, :conditions => { :published_at => 0..Time.now.utc.to_i }, :with => with,
                    :field_weights => { :name => 20, :description => 15, :notes => 5, :tag_names => 10 })
    else
      published.primitive_search(query)
    end
  rescue ThinkingSphinx::ConnectionError => e
    APP_CONFIG['thinking_sphinx'] = false
    raise e
  end

  def self.primitive_search(query, join = "AND")
    where(primitive_search_conditions(query, join))
  end

  def similar_episodes
    if APP_CONFIG['thinking_sphinx']
      self.class.search("#{name} #{tag_names}", :without_ids => [id],
            :conditions => { :published_at => 0..Time.now.utc.to_i },
            :match_mode => :any, :page => 1, :per_page => 5,
            :field_weights => { :name => 20, :description => 15, :notes => 5, :tag_names => 10 })
    else
      self.class.published.limit(5).primitive_search(name, "OR")
    end
  rescue ThinkingSphinx::ConnectionError => e
    APP_CONFIG['thinking_sphinx'] = false
    raise e
  end

  def full_name
    "\##{position} #{name}"
  end

  def tag_names=(names)
    self.tags = Tag.with_names(names.split(/\s+/))
  end

  def tag_names
    tags.map(&:name).join(' ')
  end

  def to_param
    [position, permalink].join('-')
  end

  def asset_name
 #   [padded_position, permalink].join('-')
    [padded_position, "test"].join('-')

  end

  def padded_position
    position.to_s.rjust(3, "0")
  end

  def last_published?
    self == self.class.published.last
  end

  def published?
    published_at <= Time.zone.now
  end

  def duration
    if seconds
      min, sec = *seconds.divmod(60)
      [min, sec.to_s.rjust(2, '0')].join(':')
    end
  end

  def duration=(duration)
    if duration.present?
      min, sec = *duration.split(':').map(&:to_i)
      self.seconds = min*60 + sec
    end
  end

  def self.find_by_param!(param)
    find_by_position!(param.to_i)
  end

  def asset_url(path, ext = nil)
   # "http://media.railscasts.com/assets/episodes/#{path}/#{asset_name}" + (ext ? ".#{ext}" : "")
    "http://eappscasts.com/assets/#{path}/#{asset_name}" + (ext ? ".#{ext}" : "")
  end

  def files
    [
   #   {:name => "source code", :info => "Project Files in Zip",   :url => asset_url("sources", "zip"),    :size => file_size("zip")},
      {:name => "mp4",         :info => "Full Size H.264 Video",  :url => asset_url("videos", "mp4"),  :size => file_size("mp4")},
      {:name => "m4v",         :info => "Smaller H.264 Video",    :url => asset_url("videos", "m4v"),  :size => file_size("m4v")},
      {:name => "webm",        :info => "Full Size VP8 Video",    :url => asset_url("videos", "webm"), :size => file_size("webm")},
      {:name => "ogv",         :info => "Full Size Theora Video", :url => asset_url("videos", "ogv"),  :size => file_size("ogv")},
    ]
  end

  def file_size(ext)
    (file_sizes && file_sizes[ext]).to_i
  end

  # TODO test me
  def available_files
    files.select { |f| f[:size].to_i > 0 }
  end

  def load_file_sizes
    self.file_sizes = {}
    files.each do |file|
      ext = file[:url][/\w+$/]
     self.file_sizes[ext] = fetch_file_size(file[:url])
   end
  end

  def fetch_file_size(path)
    url = URI.parse(path)
    response = Net::HTTP.start(url.host, 80) do |http|
      http.request_head(url.path)
    end
    if response.code == "200"
      response["content-length"]
    end
  end

  def previous
    self.class.where("position < ?", position).order("position desc").first
  end

  def next
    self.class.where("position > ?", position).order("position").first
  end

  private

  def self.primitive_search_conditions(query, join)
    query.split(/\s+/).map do |word|
      '(' + %w[name description notes].map { |col| "#{col} LIKE #{sanitize('%' + word.to_s + '%')}" }.join(' OR ') + ')'
    end.join(" #{join} ")
  end

  def set_permalink
    self.permalink = name.downcase.gsub(/[^0-9a-z]+/, ' ').strip.gsub(' ', '-') if name
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  load_and_authorize_resource :find_by => :param

  def index
    @tag = Tag.find(params[:tag_id]) if params[:tag_id]
    if params[:search].blank?
      @episodes = (@tag ? @tag.episodes : Episode).accessible_by(current_ability).recent
    else
      @episodes = Episode.search_published(params[:search], params[:tag_id])
    end
    respond_to do |format|
      format.html { @episodes = @episodes.paginate(:page => params[:page], :per_page => episodes_per_page) }
      format.rss
    end
  end

  def show
    if !current_user
      store_target_location
      redirect_to login_path , :notice => "To watch the episode ! Please Signup or Login"
      return
    end
    if params[:id] != @episode.to_param
      headers["Status"] = "301 Moved Permanently"
      redirect_to episode_url(@episode)
    else
      @comment = Comment.new(:episode => @episode, :user => current_user)
    end
  end

  def new
    @episode.position = Episode.maximum(:position).to_i + 1
  end

  def create
    @episode.load_file_sizes
    if @episode.save
      redirect_to @episode, :notice => "Successfully created episode."
    else
      render :new
    end
  end

  def edit
  end

  def update
    @episode.load_file_sizes
    if @episode.update_attributes(params[:episode])
      redirect_to @episode, :notice => "Successfully updated episode."
    else
      render :edit
    end
  end

  private

  def episodes_per_page
    case params[:view]
    when "list" then 40
    when "grid" then 24
    else 10
    end
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def episode_video_tag(episode)
    video_tag episode.asset_url("videos"), :poster => "/assets/episodes/posters/loading#{800 if episode.legacy?}.png", :width => (episode.legacy? ? 800 : 960), :height => 600
  end
end

app/views/episodes/_comments.html.erb
<div id="comments">
  <%= nested_comments @episode.comments.includes(:user).arrange(:order => "created_at asc") %>
  <%= render "comments/form" %>
</div>

app/views/episodes/_episode.html.erb
<div class="episode">
  <div class="screenshot"><a href="/"><%= image_tag("stills/#{episode.asset_name}.png", :size => "200x125", :alt => episode.name)%></a></div>
  <div class="main">
    <div class="info">
      <span class="number">Episode #<%= episode.position %></span> &ndash;
      <span class="published_at"><%= episode.published_at.strftime('%b %d, %Y') %></span>
      <% unless episode.published? %>
        <span class="unreleased">NOT YET RELEASED</span>
      <% end %>
    </div>
    <h2><%= link_to episode.name, episode %></h2>
    <div class="description"><%= episode.description %></div>
    <div class="watch">
      <%= link_to "Watch Episode", episode_path(episode, :autoplay => true), :class => "watch_button" %>
      <span class="stats">(<%= pluralize (episode.seconds/60).round, "minute" %>, <%= link_to pluralize(episode.comments.size, "comment"), episode_path(episode, :view => "comments") %>)</span>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/episodes/_form.html.erb
<div class="content">
  <p><strong>Please follow the <%= link_to "Contributor Guidelines", contributors_path %>.</strong></p>
  <%= form_for @episode do |f| %>
    <%= f.error_messages %>
    <%= field f, :position %>
    <%= field f, :name %>
    <%= field f, :tag_names, :label => "Tags" %>
    <%= field f, :description, :type => :text_area, :rows => 6 %>
    <%= field f, :notes, :type => :text_area, :rows => 20, :cols => 80 %>
    <%= field f, :published_at, :type => :date_select, :label => "Publish Date" %>
    <%= field f, :duration %>
    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>

app/views/episodes/_show_notes.html.erb
<% if can? :edit, @episode %>
  <div class="actions episode_actions"><%= link_to "Edit", edit_episode_path(@episode) %></div>
<% end %>

<div class="extra_nav">
  <% if @episode.asciicasts? %>
    <span class="asciicasts">
      <%= image_tag "icons/asciicasts.png", :size => "12x15", :class => "icon" %>
      <%= link_to "Read on ASCIIcasts", "http://asciicasts.com/episodes/#{@episode.to_param}" %>
    </span>
  <% end %>
  <% if @episode.file_sizes && @episode.file_sizes["zip"] %>
    <span class="browse_code">
      <%= image_tag "icons/browse_code.png", :size => "22x21", :class => "icon" %>
      <%= link_to "Browse Source Code", "http://github.com/railscasts/episode-#{@episode.position}" %>
    </span>
  <% end %>
</div>

<div class="show_notes">
  <%= @episode.notes %>
</div>

app/views/episodes/_similar.html.erb
<div class="similar">
  <div class="full">
    <%= render @episode.similar_episodes %>
  </div>
</div>

app/views/episodes/edit.html.erb
<% title "Edit Episode" %>

<%= render :partial => 'form' %>

app/views/episodes/index.html.erb
<% title "Enterprise Application Screencasts", false %>

<div class="content">
 <div class="row">
  <div class="span-4">
    <div class="episode_views">
      View:
      <span class="view"><%= link_to_unless params[:view] == "full", image_tag("views/full.png", :size => "15x10"), params.merge(:view => "full", :page => nil), :title => "Full View" %></span>
      <span class="view"><%= link_to_unless params[:view] == "list", image_tag("views/list.png", :size => "14x10"), params.merge(:view => "list", :page => nil), :title => "List View" %></span>
      <span class="view"><%= link_to_unless params[:view] == "grid", image_tag("views/grid.png", :size => "11x10"), params.merge(:view => nil, :page => nil), :title => "Grid View" %></span>
    </div>
    <div class="categories">
      <h2>Categories</h2>
      <ul>
      <% for tag in Tag.order("name") %>
        <li><%= link_to_unless(params[:tag_id].to_i == tag.id, tag.display_name, params.merge(:tag_id => tag.id, :page => nil)) %></li>
      <% end %>
      </ul>
    </div>
  </div>

  <div class="span-8">
  <div class="episodes">
    <% if @tag || params[:search].present? %>
      <div class="filters">
        <strong>Filtering:</strong>
        <% if params[:search].present? %>
          <span class="filter"><%= params[:search] %> <%= link_to "x", params.merge(:search => nil, :page => nil) %></span>
        <% end %>
        <% if @tag %>
          <span class="filter"><%= @tag.display_name %> <%= link_to "x", params.merge(:tag_id => nil, :page => nil) %></span>
        <% end %>
      </div>
    <% end %>
    <% if @episodes.empty? %>
      <p class="content">No episodes found. <%= link_to "See all episodes.", episodes_path %></p>
    <% else %>
      <% if params[:view] == "full" %>
        <div class="full">
          <%= render @episodes %>
        </div>
      <% elsif params[:view] == "list" %>
        <table class="list">
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Comments</th>
            <th>Duration</th>
            <th>Released</th>
          </tr>
          <% for episode in @episodes %>
            <tr>
              <td><%= episode.position %></td>
              <td><%= link_to episode.name, episode %></td>
              <td><%= link_to pluralize(episode.comments.size, "comment"), episode_path(episode, :view => "comments"), :class => "comment_count" %></td>
              <td><%= pluralize (episode.seconds/60).round, "minute" %></td>
              <td><%= episode.published_at.strftime('%b %d, %Y') %></td>
            </tr>
          <% end %>
        </table>
      <% elsif params[:view].nil? %>
        <div class="grid">
          <% for episode in @episodes %>
            <div class="episode">
              <div class="screenshot"><%= link_to image_tag("/assets/stills/#{episode.asset_name}.png", :size => "200x125"), episode %></div>
              <div class="name">
                #<%= episode.position %>
                <%= link_to episode.name, episode %>
              </div>
            </div>
          <% end %>
          <div class="clear"></div>
        </div>
      <% end %>

      <%= will_paginate :previous_label => h("< Previous Page"),  :next_label => h("Next Page >") %>
    <% end %>
  </div>
  <% if can? :create, :episodes %>
    <div class="actions"><%= link_to "New Episode", new_episode_path %></div>
  <% end %>
  </div>
 </div>
</div>

app/views/episodes/new.html.erb
<% title "New Episode" %>

<%= render :partial => 'form' %>

app/views/episodes/show.html.erb
<% title @episode.full_name, false %>

<div id="episode" class="<%= "legacy" if @episode.legacy? %>">
  <% if params[:autoplay] %>
    <div id="video_wrapper"><%= episode_video_tag @episode %></div>
  <% else %>
    <script type="text/html" id="video_template">
      <%= episode_video_tag @episode %>
    </script>
  <% end %>
  <div class="info<%= " video_info" if params[:autoplay] %>">
    <div class="screenshot"><%= link_to image_tag("stills/#{@episode.asset_name}.png", :size => "200x125", :alt => @episode.name), {:autoplay => true}, :class => "play_video" %></div>
    <h1>
      <span class="position">#<%= @episode.position %></span>
      <%= @episode.name %>
    </h1>
    <div class="details">
      <%= @episode.published_at.strftime('%b %d, %Y') %> |
      <%= pluralize (@episode.seconds/60).round, "minute" %> |
      <%= raw @episode.tags.map { |tag| link_to tag.display_name, root_path(:tag_id => tag) }.join(", ") %>
      <% unless @episode.published? %>
        <span class="unreleased">NOT YET RELEASED</span>
      <% end %>
    </div>
    <div class="description"><%= @episode.description %></div>
    <div class="watch">
      <%= link_to({:autoplay => true}, {:class => "play_video watch_button"}) do %>
        Click to Play Video &#9654;
      <% end %>
    </div>
    <div class="social">
      <a href="http://twitter.com/share" class="twitter-share-button" data-url="<%= episode_url(@episode) %>" data-text="Watching <%= @episode.name %> on RailsCasts" data-count="horizontal" data-via="railscasts">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    </div>
    <ul class="downloads horizontal">
      <li>Download:</li>
      <% for file in @episode.available_files %>
        <li>
          <%= link_to file[:name], file[:url] %>
          <span class="overlay"><%= file[:info] %> (<%= number_to_human_size(file[:size]) %>)</span>
        </li>
      <% end %>
    </ul>
    <div class="clear"></div>
  </div>
  <ul class="nav horizontal">
    <li class="selected"><%= tab_link "Show Notes", :view => nil %></li>
    <li><%= tab_link pluralize(@episode.comments.size, "Comment"), :view => "comments" %></li>
    <li><%= tab_link "Similar Episodes", :view => "similar" %></li>
    <%= content_tag :li, link_to("Next Episode >", @episode.next), :class => "next" if !@episode.last_published? && @episode.next %>
    <%= content_tag :li, link_to("< Previous Episode", @episode.previous), :class => "previous" if @episode.previous %>
  </ul>
  <div class="nav_section">
    <%= %w[comments similar].include?(params[:view]) ? render(params[:view]) : render("show_notes") %>
  </div>
</div>

app/views/episodes/show.js.erb
$("#episode .nav_section").html("<%= escape_javascript(%w[comments similar].include?(params[:view]) ? render(params[:view]) : render("show_notes")) %>");