config/routes.rb
Eappscasts::Application.routes.draw do

  
    root :to => "info#home"

    match "auth/:provider/callback" => "sessions#create"
    match "/auth/failure", :to => "sessions#failure"
    match "twitter_login" => "sessions#twitter_login" ,:as=>"twitter_login"
    match "twitter_login_check" => "sessions#twitter_login_check" ,:as=>"twitter_login_check"
    match "/signout" => "sessions#destroy", :as => :signout
    match "about" => "info#about", :as => "about"
    match "login" => "info#login", :as => "login"
    match "opensource" => "info#opensource", :as => "opensource"
    match "give_back" => "info#give_back", :as => "give_back"
    match "contributors" => "info#contributors", :as => "contributors"
    match "logout" => "users#logout", :as => "logout"
    match "feedback" => "feedback_messages#new", :as => "feedback"
    match "episodes/archive" => redirect("/?view=list")
    match 'unsubscribe/:token' => 'users#unsubscribe', :as => "unsubscribe"
    post "versions/:id/revert" => "versions#revert", :as => "revert_version"
    get '/signup' => 'info#signup', :as => :signup  
  
    resources :users do
      member { put :ban }
    end
    resources :comments
    resources :episodes
    resources :feedback_messages

    match "tags/:id" => redirect("/?tag_id=%{id}")
  
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
end

app/views/layouts/_footer.html.erb
<hr>

<div class="footer">

</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
	    <li class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span
	      <span class="icon-bar"></span>
        </li>
	  <div class="nav-collapse">
        <ul class="nav">
			<li class="<%=  activ_link("home") %>" ><%= link_to "Home", root_url %></li>
                        <li class="<%=  activ_link("about") %>" ><%= link_to "About eAppsCasts", about_path %></li>
			
                        <% if current_user %>
			<li><%= link_to_unless_current "Feedback", feedback_path %></li>
                        <li>
  			 Welcome <%= current_user.name %>! <%= link_to "Sign Out", signout_path %>
                        </li>
  			<% else %>
                         <li class="<%=  activ_link("login") %>" ><%= link_to "Signup or Login", login_path %></li>
                         
  			<% end %>
			<% if current_user %>
			<div class="navbar-search-login">
                         <%  else %>
                          <div class="navbar-search">
                          <%  end %>
				<%= form_tag episodes_path, :method => "get" do %>
				<%= text_field_tag :search, params[:search], :size => 35 %>
				<%= submit_tag "Search Episodes", :name => nil %>
				<% end %>
			</div>
	 	</ul>
	  </div>
    </div>
  </div>
</div>

app/views/layouts/_stylesheets.html.erb
<style type="text/css">
  body {
    padding-top: 80px;
    padding-bottom: 40px;
  }
</style>

<%= stylesheet_link_tag "application", "bootstrap" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	    <title><%= content_for?(:title) ? yield(:title) : "Enterprise Application Screencasts" %> - eAppsCasts</title>
	    <meta name="description" content="Enterprise Application screencasts containing tips, tricks and tutorials."/>
	    <meta name="keywords" content="screencasts, tutorials, training, podcasts, programming" />
	    <link rel="alternate" type="application/rss+xml" title="Episodes RSS" href="http://feeds.feedburner.com/appscasts" />
      <%= render 'layouts/stylesheets'%>

      <%= javascript_include_tag "application" %>
  		<script type="text/javascript" src="http://cdn.sublimevideo.net/js/taxd0b6d.js"></script>

	    <%= csrf_meta_tag %>
	    <%= yield(:head) %>
	</head>
	<body>
		<%= render 'layouts/header' %>
  
	    <% flash.each do |name, msg| %>
	      <%= content_tag(:div, raw(msg), :id => "flash_#{name}") %>
	    <% end %>

		    <div class="container">
		      <% if show_title? %>
		        <h1 class="content"><%= yield(:title) %></h1>
		      <% end %>

		      <%= yield %>
		    </div>

	    <%= render 'layouts/footer'%>

	</body>
</html>